title: "Brian Pozar"
description: "CV, apps, and writing by Brian Pozar."
url: "https://www.pozar.net"
baseurl: ""

markdown: kramdown
theme: null
permalink: /blog/:year/:month/:day/:title/

collections:
  posts:
    output: true

# Simple navigation config to keep things DRY in templates
nav:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Apps"
    url: "/apps/"
  - title: "Articles"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"

headshot: "/assets/img/headshot.jpeg"
